### ISSUE TITLE
Add validation of the changelog

### ISSUE THREAD

**Issue by aroemen** [mindsers/changelog-reader-action#18]
It would be nice to have some basic validation of the changelog to ensure developers are incrementing the version in accordance with Semantic Versioning standards and Keep a Changelog formatting.

Proposed Validation Rules:
1. The version is a valid semantic version.
1. The versions are sorted in reverse chronological order.
1. That each specified section (Added, Changed, Removed, etc) actually has changes listed underneath them.
1. Enforce that only specified types are allowed for changes between versions.
    1. Major releases allow sections for added, removed, changed, deprecated, fixed, and security
    1. Minor releases allow sections for added (non-breaking), changed (non-breaking), deprecated, fixed, and security
    1. Patch and below releases allow sections for fixed, and security

Adding an input param such as `validation_depth` would allow users to configure how much, if any, of their changelog they would like to have validated. Setting a depth to 0 would, in sense, disable validation. This would be a helpful setting in case the codebase maybe had a change log that didn't follow standards when it was started.

**Comment by mindsers** [comment]
This is a great idea but I can't see it implemented in this project (or we'll need to talk more about it). As I started to explain it in https://github.com/mindsers/changelog-reader-action/pull/17#discussion_r475318851 and in the [README.md](https://github.com/mindsers/changelog-reader-action#changelog-reader):

> This action only work if your CHANGELOG.md file follows the Keep a Changelog standard **for now**.

My point is: this action is only a CHANGELOG reader and I don't know if altering the `CHANGELOG.md` data or enforcing specific format/standard is relevant. But I could definitely by another action that works with this one.

I'm open to discussion though 😉

**Comment by aroemen** [comment]
I feel it is very relevant in this action. Since the entire action is geared around only working if you follow the Keep a Changelog standard, I feel that having validation to enforce those standards is a must have.  The validation logic could also help some developers keep their versioning practices follow in line with how semantic versioning requires them to be. What good is a Changelog **reader** if the changelog it wants to read is invalid?

**Comment by mindsers** [comment]
I think the validation step should appear way before in the developer workflow. Using this action means you already wrote the `CHANGELOG.md` (in a great or bad way), pushed it and even tagged it. 

So, having the reader failing because it wants to tell your CHANGELOG is not valid at this time could be really frustrating I guess. You're not writing your CHANGELOG anymore at the time in the process.

In comparison, having an validator failing because your `CHANGELOG.md` is not valid when you push code on a PR (your feature branch) is really useful!

**Comment by mindsers** [comment]
That being said, someone could use this action in other places in the dev workflow. 

I mean, we could use it as a check for PRs to only validate the content of the changelog before merging the code but not actually getting the content. But in that case most of the rules don't apply because changes are added to the "Unreleased" section (no semver).

We could also use it to validate changelog on `master` but it won't prevent tagging  or publishing since the code is already on master.. 😞

**Comment by mindsers** [comment]
So I think it could be useful in some cases but as an option but not as a default behavior.

**Comment by aroemen** [comment]
I'm thinking along the same lines. I can see this action being used in multiple places. I can make the default behavior not do any validation if that is what you'd like.

**Comment by aroemen** [comment]
@mindsers have you had any other thoughts on this enhancement? Do you want to have this in your action here or should this be a separate action?

**Comment by mindsers** [comment]
@aroemen We'll add it to the action but I need to read a bit more the related PR 😉

**Comment by mindsers** [comment]
@all-contributors please add @aroemen for idea
