### ISSUE TITLE
Replace newline with spaces

### ISSUE THREAD

**Issue by yi-Xu-0100** [mindsers/changelog-reader-action#40]
The output body in Markdown format with a newline will make the release body keep newlines.

The one newline should show as space with Markdown format, and the multi newlines should show as one newline.

Could you parse the changelog body with the correct format to output?

**Comment by mindsers** [comment]
Hi @yi-Xu-0100, thanks for taking the time to open this issue ! ☺️

Can you give more information about what you want or your specific use case ? Because I'm not sure to correctly understand.

Currently, `changelog-reader-action` should return the markdown content as it is written in the markdown file in your repo. Updating the file with the correct syntax should do the work. I don't really see why the action should alterate the content of your markdown file.

So, do not hesitate to add more information to this issue! And thanks again for your interest on this project!

**Comment by yi-Xu-0100** [comment]
@mindsers Sorry for the delay reply. Here is the test repo: https://github.com/yi-Xu-0100/test

See the markdown format in https://github.com/yi-Xu-0100/test/blame/main/CHANGELOG.md

```md
## [1.16.0](https://github.com/vivaxy/vscode-conventional-commits/compare/v1.15.1...v1.16.0) (2021-03-02)

### Features

- ✨ add new scope selection
  ([#51](https://github.com/vivaxy/vscode-conventional-commits/issues/51))
  ([05a5b39](https://github.com/vivaxy/vscode-conventional-commits/commit/05a5b39c3e677104a9999e069ab74e8818212bc5)),
  closes [#50](https://github.com/vivaxy/vscode-conventional-commits/issues/50)
```

It uses space to fold the long sentence. But the body of the [release v1.16.0](https://github.com/yi-Xu-0100/test/releases/tag/v1.16.0) will be broken for it.

**Comment by yi-Xu-0100** [comment]
I use `prettier --write CHANGELOG.md  --prose-wrap never` fix it. 😅

**Comment by mindsers** [comment]
Hey! Thanks for letting me know and closing the issue! I'm glad you found a solution for this.
